<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJaukzco\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJaukzco/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJaukzco.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJaukzco\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJaukzco\appProdProjectContainer([
    'container.build_hash' => 'Jaukzco',
    'container.build_id' => '12717230',
    'container.build_time' => 1589601216,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJaukzco');
